# Generated by Django 5.0.1 on 2024-02-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Year_And_Month', models.DateField()),
                ('Image', models.ImageField(upload_to='Images')),
            ],
        ),
    ]
